spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 3000ms
        max-idle: 20
        min-idle: 2
    timeout: 5000ms
logging:
  level:
    com.homeward.website.mapper: debug
